### ISSUE TITLE
Examples use the A-to-A usb instead of USB-mini

### ISSUE THREAD

**Issue by ozrien** [CrossTheRoadElec/HERO-STM32F4-Applications#2]
The examples use OTG_FS, which wires to the USB host connector (type A).  This means you have to use an A-to-A usb cable.

We should add another build configuration to use OTG_HS, which wires to the peripheral mini USB connector (mini B).

**Comment by ozrien** [comment]
Use a similar strategy as this...
https://github.com/ozrien/STM32Cube_FW_F4_V1.21.0/blob/22b971ed10b917b16ec94ca9ff794b2b616f838a/Projects/STM324x9I_EVAL/Applications/Display/LTDC_Paint/Src/usbh_conf.c#L252

https://github.com/ozrien/STM32Cube_FW_F4_V1.21.0/blob/22b971ed10b917b16ec94ca9ff794b2b616f838a/Projects/STM324x9I_EVAL/Applications/Display/LTDC_Paint/Src/usbh_conf.c#L66

**Comment by CoryNessCTR** [comment]
#5 has this fixed.
![image](https://user-images.githubusercontent.com/28712271/44111442-6f3f8e72-9fd0-11e8-88e5-79e9aea53534.png)
